## Diana

In [1]:
from tabula.tabula import Tabula
import pandas as pd
import torch

2024-11-28 14:35:19.474014: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-28 14:35:19.533652: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [17]:
file_path = '../../Data/data.csv'
data = pd.read_csv(file_path)
data.head()

,customer_age_class,region,basket_package_price_disc,internet_package_price_disc,basket_days_until_contract_end,count_previous_cancellations_0_18,internet_product_name,flag_churn
0,70 - 74,NRW,64.95,54.97,366,0,3PLAY PREMIUM HRZ,0
1,35 - 39,HSN,44.98,44.98,100,0,RED INTERNET & PHONE CABLE U,1
2,35 - 39,NRW,54.98,54.98,30,0,RED INTERNET & PHONE CABLE U,1
3,35 - 39,HSN,209.84,209.84,30,0,VF CABLEMAX,1
4,25 - 29,NRW,63.98,63.98,123,0,GIGAZUHAUSE KABEL,1

In [3]:
columns = ['region', 'customer_age_class', 'basket_package_price_disc',   
           'internet_package_price_disc', 'basket_days_until_contract_end',
           'count_previous_cancellations_0_18', 'internet_product_name',
           'flag_churn']
data = data[columns]

In [4]:
data.head()

,region,customer_age_class,basket_package_price_disc,internet_package_price_disc,basket_days_until_contract_end,count_previous_cancellations_0_18,internet_product_name,flag_churn
0,NRW,70 - 74,64.95,54.97,366,0,3PLAY PREMIUM HRZ,0
1,HSN,35 - 39,44.98,44.98,100,0,RED INTERNET & PHONE CABLE U,1
2,NRW,35 - 39,54.98,54.98,30,0,RED INTERNET & PHONE CABLE U,1
3,HSN,35 - 39,209.84,209.84,30,0,VF CABLEMAX,1
4,NRW,25 - 29,63.98,63.98,123,0,GIGAZUHAUSE KABEL,1

In [5]:
# gpt model
categorical_columns = ['region', 'customer_age_class', 'internet_product_name']
model = Tabula(llm='gpt2', experiment_dir = "adult_training", batch_size=16, epochs=5, categorical_columns = categorical_columns)

/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [6]:
model.fit(data)

/opt/conda/lib/python3.10/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '

In [7]:
synthetic_data_diana = model.sample(n_samples=10000)

10096it [02:25, 69.35it/s]
/home/jupyter/Students/2024_Mayilyan_LLM/LLM_based/Diana/tabula/tabula.py:179: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[self.label_encoder_list[i]['column']] = pd.to_numeric(data[self.label_encoder_list[i]['column']], errors='coerce')

In [8]:
synthetic_data_diana

,region,customer_age_class,basket_package_price_disc,internet_package_price_disc,basket_days_until_contract_end,count_previous_cancellations_0_18,internet_product_name,flag_churn
0,NRW,75 - 79,42.98,44.98,30.0,0.0,MMA MB,0.0
1,NRW,60 - 64,29.99,44.99,30.0,0.0,MMA MB,1.0
2,NRW,40 - 44,39.99,44.98,30.0,0.0,MMA MB,0.0
3,NRW,25 - 29,44.98,44.98,30.0,0.0,MMA MB,1.0
4,KBW,30 - 34,30.98,44.98,30.0,0.0,3PLAY START,1.0
...,...,...,...,...,...,...,...,...
9995,KBW,25 - 29,34.99,39.99,30.0,0.0,MMA MB,1.0
9996,NRW,35 - 39,49.97,49.97,30.0,1.0,3PLAY PREMIUM MTA,1.0
9997,KBW,70 - 74,34.99,34.99,30.0,0.0,3PLAY START,1.0
9998,NRW,40 - 44,44.98,39.99,30.0,0.0,MMA MB,1.0
9999,NRW,35 - 39,39.99,52.97,30.0,0.0,TREUEPLUS BASIS,0.0

In [10]:
synthetic_data_diana.to_csv('diana_data.csv', index=False)

In [29]:
#Shows that all the synthetic values are from the original value set
set1 = set(synthetic_data_diana['internet_product_name'].unique())
set2 = set(data['internet_product_name'].unique())
list(set1-set2)

[]